<x-layouts.app :title="'VoyagerRent — '.__('ui.search_cars')">
    <section class="overflow-hidden bg-slate-950 px-4 pb-28 pt-16 text-white sm:px-6 lg:px-8 lg:pt-24">
        <div class="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center">
            <div class="relative z-10"><p class="inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-sm font-semibold text-cyan-200">{{ __('ui.hero_eyebrow') }}</p><h1 class="mt-6 max-w-2xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">{{ __('ui.hero_title') }}</h1><p class="mt-6 max-w-xl text-lg leading-8 text-slate-300">{{ __('ui.hero_text') }}</p><div class="mt-8 flex flex-wrap gap-4"><a href="#search" class="rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-slate-950 shadow-lg shadow-cyan-400/20 transition hover:bg-cyan-300">{{ __('ui.explore_inventory') }}</a><a href="#how-it-works" class="rounded-xl border border-white/20 px-5 py-3 text-sm font-bold transition hover:bg-white/10">{{ __('ui.how_it_works') }}</a></div><div class="mt-12 flex items-center gap-3 text-sm text-slate-400"><span class="grid h-8 w-8 place-items-center rounded-full bg-emerald-400/20 text-emerald-300">✓</span>{{ __('ui.trusted_companies') }}</div></div>
            <div class="relative min-h-80"><div class="absolute inset-0 rounded-[2.5rem] bg-gradient-to-br from-cyan-400 via-blue-500 to-indigo-700 opacity-90"></div><div class="absolute inset-8 rounded-[2rem] border border-white/30 bg-slate-950/20 backdrop-blur"><div class="flex h-full items-center justify-center text-9xl drop-shadow-2xl" aria-hidden="true">🚘</div></div><div class="absolute -bottom-6 -start-6 rounded-2xl bg-white p-4 text-slate-900 shadow-xl"><p class="text-xs font-bold uppercase tracking-widest text-cyan-600">One platform</p><p class="mt-1 font-bold">Booking to return</p></div></div>
        </div>
    </section>
    <livewire:marketplace-search />
    <section id="how-it-works" class="bg-white px-4 py-20 sm:px-6 lg:px-8 dark:bg-slate-950"><div class="mx-auto max-w-7xl"><div class="max-w-2xl"><p class="text-sm font-bold uppercase tracking-widest text-cyan-600">VoyagerRent</p><h2 class="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{{ __('ui.how_title') }}</h2></div><div class="mt-10 grid gap-6 md:grid-cols-3"><article class="rounded-3xl border border-slate-200 p-6 dark:border-slate-800"><span class="grid h-11 w-11 place-items-center rounded-xl bg-cyan-100 text-lg dark:bg-cyan-950">01</span><h3 class="mt-5 text-lg font-bold">{{ __('ui.how_compare_title') }}</h3><p class="mt-2 leading-7 text-slate-600 dark:text-slate-300">{{ __('ui.how_compare_text') }}</p></article><article class="rounded-3xl border border-slate-200 p-6 dark:border-slate-800"><span class="grid h-11 w-11 place-items-center rounded-xl bg-cyan-100 text-lg dark:bg-cyan-950">02</span><h3 class="mt-5 text-lg font-bold">{{ __('ui.how_manage_title') }}</h3><p class="mt-2 leading-7 text-slate-600 dark:text-slate-300">{{ __('ui.how_manage_text') }}</p></article><article class="rounded-3xl border border-slate-200 p-6 dark:border-slate-800"><span class="grid h-11 w-11 place-items-center rounded-xl bg-cyan-100 text-lg dark:bg-cyan-950">03</span><h3 class="mt-5 text-lg font-bold">{{ __('ui.how_support_title') }}</h3><p class="mt-2 leading-7 text-slate-600 dark:text-slate-300">{{ __('ui.how_support_text') }}</p></article></div></div></section>
</x-layouts.app>
